title: "Akhilesh K M"
description: "AWS Cloud Engineer | Senior Software Engineer | Portfolio & Resume"
remote_theme: "mmistakes/minimal-mistakes@v4.27.3"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
